#!/bin/bash
if [ $# -lt 2 ]; then
    echo USAGE: $0 DOMAIN EMAIL
    exit 1;
fi
DOMAIN=$1
EMAIL=$2
sudo certbot certonly --standalone -d $DOMAIN
sudo certbot certonly --manual --preferred-challenges=dns --email $EMAIL --server 'https://acme-v02.api.letsencrypt.org/directory' --agree-tos -d "*.$DOMAIN"
