#!/bin/bash
sudo dnf -y remove vim gvim
sudo dnf -y builddep vim-X11 vim
sudo dnf -y install ruby ruby-devel lua lua-devel luajit luajit-devel ctags git python python-devel python3 python3-devel tcl-devel perl perl-devel perl-ExtUtils-ParseXS perl-ExtUtils-XSpp perl-ExtUtils-CBuilder perl-ExtUtils-Embed
cd /data/src/;
git clone https://github.com/vim/vim.git
cd vim;
CFLAGS=-fPIC ./configure --with-features=huge --enable-multibyte --enable-rubyinterp=yes --enable-python3interp=yes --with-python3-config-dir=$(python3-config --configdir) --enable-perlinterp=yes --enable-luainterp=yes --enable-gui=gtk3 --with-x --enable-cscope --prefix=/usr/local --with-tlib=ncurses --enable-fontset --enable-gtk3-check --enable-gnome-check --enable-fail-if-missing
make VIMRUNTIMEDIR=/usr/local/share/vim/vim82
sudo make install;
cd /usr/bin;
sudo ln -s /usr/local/bin/vim;
sudo ln -s /usr/local/bin/vimdiff;
sudo ln -s /usr/local/bin/gvim;
sudo ln -s /usr/local/bin/gvimdiff;
cd -
