#!/bin/bash
sudo dnf -y install https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm
sudo dnf -y install https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm
sudo dnf -y install gstreamer1-plugins-{bad-\*,good-\*,base} gstreamer1-plugin-openh264 gstreamer1-libav --exclude=gstreamer1-plugins-bad-free-devel
sudo dnf -y install lame\* --exclude=lame-devel
sudo dnf -y install mplayer mencoder
sudo dnf -y install alsa-lib-devel
sudo dnf -y install pulseaudio-libs-devel
sudo dnf -y install ffmpeg ffmpeg-devel ffmpeg-libs
sudo dnf -y group upgrade --with-optional Multimedia
sudo dnf -y install gimp
