alias a='';
alias A='';
alias b='';
alias B='';
alias c='';
alias cd='cd -P';
alias C='/opt/php-7.0/bin/php /opt/bin/composer.phar';
alias d='dfultra';
alias D='';
alias e='';
alias E='';
alias f='find';
alias fbm='mplayer -nolirc -vo fbdev2:/dev/fb0 -vf scale=1250:-3';
alias g='google-chrome'
alias G='google'
alias gl='git log -p --decorate --stat --dense --left-right --raw --full-history --cumulative'
alias grep='grep -E';
alias G='google';
alias h='help';
alias H='hostname'
alias i='inxi -xxxABCDGImMNRSw';
alias ip='ip -c';
alias I='';
alias j='journalctl -f';
alias J='';
alias k='krunner';
alias K='';
alias l='\ls  --time-style="+%Y%m%d%H%M%S" --group-directories-first --color=always -lAnFtr';
alias L='less -SRC';
alias mp='mplayer';
alias m='function pm() { mount | sed -r "s/(on|type)//g" | column -t --table-columns="NAME,MOUNTPOINT,TYPE,OPTS" -W "OPTS" -c 1000; }; pm | grep NAME; pm | grep -v NAME | sort -k 3,3 -r;'
alias M='';
alias n='';
alias N='';
alias o='';
alias O='';
#alias p='ps --headers axm -e --format args:1000,ppid:7,pid:6,nlwp:7,spid:7,%mem:7,%cpu:7,atime:7,f:4,nwchan:8,vsize:16,rss:20,euser:20,longtname:5,lstart:25,bsdstart:7,bsdstart:7,pending:10,ignored:10,caught:9,blocked:10,ni:5,etime:10,class:6,uunit:20,unit:30,utsns:10,userns:10,pidns:10,netns:10,mntns:10,ipcns:10,cpuid:6,longtname:6,m_trs:6,tpgid:8,tid:6,tgid:7,rsz:5,svuid:8,svgid:8,fsuser:8,supgrp:20,supgid:20,fsuid:7,stat:7,stackp:10,esp:10,eip:10,slice:30,m_size:7,sid:6,fsgroup:9,fsgid:7,lsession:10,lsession:7,seat:7,sched:6,ruser:8,ruid:7,rtprio:8';
alias p='ps auxf';
alias P='pstree -AanlcpuSshgnZ';
alias q='exit';
alias Q='';
alias r='';
alias R='';
alias s='stat_fullopts';
alias S='ss -rnaoempbE';
alias t='top';
alias T="tree -a --inodes --device -CfiqpughDFt";
alias u='ulimit -a';
alias U='';
alias v='vim';
alias V='';
alias w="w -fu";
alias W='who -all';
alias x='';
alias X='';
alias y='';
alias Y='';
alias z='';
alias Z='';
alias lb='lsblk -a --output-all';
alias ll='l';
alias lt='l -Str';
alias lh='l -thSr';
alias man='manwrapper';
alias parole='kpcli --kdb "$HOME/keys/kee-parole.kdbx" --histfile /dev/null';
alias sshvpn='sshuttle -r myuserthere@there 0.0.0.0/0 -vv --python=/Users/myuserthere/.pyenv/versions/3.9.1/bin/python3 --ssh-cmd "ssh -i ~/.ssh/id_rsa"' # --dns ( doesnt seem to work, use hosts file instead)
alias getpubip="curl ifconfig.me; echo;"
alias pactlloopback='pactl load-module module-loopback'
#alias startvnc='x11vnc -auth guess -forever -loop -noxdamage -repeat -rfbauth ~/.vnc/passwd -rfbport 5900 -shared'
alias startvnc='x11vnc -auth guess -forever -loop -noxdamage -repeat -rfbport 5900 -shared'
alias exifscrub_destructive="exiftool -overwrite_original -LensIDNumber= -SerialNumber= -LensSerialNumber= -ShutterCount= -Keywords= -Subject= -ThumbnailImage= -PhotoshopThumbnail= -XMP:All= "
alias sr="songrec"
alias ts='tmuxp load ~/tmuxp/default.yaml'
alias jellyfin='sudo su - jellyfin -c ". /etc/sysconfig/jellyfin; /usr/bin/jellyfin $JELLYFIN_WEB_OPT $JELLYFIN_RESTART_OPT $JELLYFIN_FFMPEG_OPT $JELLYFIN_SERVICE_OPT $JELLYFIN_NOWEBAPP_OPT $JELLYFIN_ADDITIONAL_OPTS"'
alias whatsapp='flatpak run io.github.mimbrero.WhatsAppDesktop'
