#!/bin/bash
{
  cat /proc/modules | cut -f 1 -d " " | while read module; do
   if [ -d "/sys/module/$module/parameters" ]; then
    ls /sys/module/$module/parameters/ | while read parameter; do
     export value=$(cat /sys/module/$module/parameters/$parameter);
     printf "%s %s %s\n" "$module" "$parameter" "$value";
    done; 
   fi; 
   echo; 
  done;
} | sed -r '/^$/d' | column -t -s ' '
