#!/bin/bash
function include_common(){ # includes common.inc.sh
  SCRIPT_ROOT=$( dirname $( dirname $(readlink -f "$0") ) );
  export USERBIN_LIB="${SCRIPT_ROOT}/lib/common.inc.sh";
  . "$USERBIN_LIB"
}
function __main__(){
  include_common
  let DEBUG=0; #defaults
  start_xtrace
  N=$1; ls -1tr | tail -n$N | while read i; do mvallsha256 $i; done;
  stop_xtrace
}
__main__ $*
