#!/bin/bash
sudo bash -c "sudo cat <<E > /etc/hosts
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
E
"
ALLOW='reddit|redd.it|linkedin'
sudo curl http://sbc.io/hosts/alternates/fakenews-gambling-porn-social/hosts \
    | sudo grep -viE "${ALLOW}" >> /etc/hosts
