#!/bin/bash
function include_common(){
  . "${HOME}/bin/lib/common.inc.sh";
}
function print_usage(){
  note_to_stdout 'USAGE' '%s [video_file]\n' "$SN";
  printf '    [video_file]    a video file\n';
  note_to_stdout 'NOTE' '%s params in "[]" are REQUIRED\n' '-';
}
function print_help(){
  export SN=$( basename $0 )
  export SPACER="";
  if [[ $# -gt 0 ]]; then 
    err_to_stderr " INVALID INVOCATION:\n $SN $*\n\n"
    print_usage;
    exit 255;
  else print_usage;
  fi;
}
function handle_params(){
  declare -a PARAMS=( ${@:1:$MAXP} );
  export NP=${#PARAMS[@]};
  if [ $NP -lt $MINP ] || [ $NP -gt $MAXP ]; then 
    err_to_stderr " $NP number of arguments provided is not in range [$MINP,$MAXP]\n";
    print_help "$*";
  fi;
  export V_NAME=$1;
  export SRT_NAME=$( echo "$V_NAME"| sed -r 's/(.+)\.[^\.]+$/\1.srt/g' );
  export D=$( ffprobe $V_NAME 2>&1 | grep Duration | awk '{ print $2; }' | sed -r 's/[,:\.]/ /g' | sed -r 's/0([0-9])/\1/g' );
  export MINS=$( echo $D  | awk '{ print $1"*60+"$2; }' | bc );
}
function handle_time_exports(){
  export NM=$( echo "$M+1" | bc );
  export H=$( echo $M'/60' | bc ) && [[ $H -lt 10 ]] && export H="0$H";
  export MP=$( echo $M'%60' | bc ) && [[ $MP -lt 10 ]] && export MP="0$MP";
  export NH=$( echo $NM'/60' | bc ) && [[ $NH -lt 10 ]] && export NH="0$NH"; 
  export NMP=$( echo $NM'%60' | bc ) && [[ $NMP -lt 10 ]] && export NMP="0$NMP";
}
function write_srt_file () {
  handle_params $*
  padl "printf '' > $SRT_NAME";
  for M in $( seq 0 $MINS ); do
    handle_time_exports;
    padl 'printf "%s\n%s:%s:00,000 --> %s:%s:00,000\nминута %s\n\n"'" $M $H $MP $NH $NMP $M "'>> '${SRT_NAME}';';
  done
}
function __main__() {
  include_common
  let DEBUG=0; #defaults
  start_xtrace
  export MAXP=1;
  export MINP=1;
  write_srt_file $*
  stop_xtrace
}
__main__ $*
