#!/bin/bash
function ee(){ echo $*;  eval $*; }
function two_hop_ssh_tunnel(){
  export LOCAL_PORT=$1
  export REMOTE_PORT=$2
  export MID_PORT=$3
  export USER1=$4
  export HOST1=$5
  export USER2=$6
  export HOST2=$7
  if [ $# -ne 7 ]; then
    echo -e "Usage:\n$0 LOCAL_PORT REMOTE_PORT MID_PORT USER1 HOST1 USER2 HOST2'";
    return 1
    fi;
    ee ssh -A -t -l $USER1 $HOST1 -L $LOCAL_PORT:localhost:$MID_PORT \
      ssh -A -t -l $USER2 $HOST2 -L $MID_PORT:localhost:$REMOTE_PORT;
    }
  function __main__(){
    two_hop_ssh_tunnel $*;
  }
__main__ $*
