#!/bin/bash

DELAY=${DELAY:-10}
LOOP=${LOOP:-0}
R=`realpath $1`
D=`dirname $R`
pushd $D > /dev/null
F=`basename $R`
N=`webpinfo -summary $F | grep frames | sed -e 's/.* \([0-9]*\)$/\1/'`
webpinfo -summary $F
DUR=`webpinfo -summary $F | grep Duration | head -1 |  sed -e 's/.* \([0-9]*\)$/\1/'`
if [ -z $DUR ]; then
    let DUR=0;
fi
echo DUR: $DUR
if (( $DUR > 0 )); then
  let DELAY=$DUR
fi
PFX=`echo -n $F | sed -e 's/^\(.*\).webp$/\1/'`
if [ -z $PFX ]; then
  PFX=$F
fi

echo "converting $N FRAMES from $F 
working dir $D
file stem '$PFX'"

for i in $(seq -f "%05g" 1 $N)
do
  webpmux -get frame $i $F -o $PFX.$i.webp
  dwebp $PFX.$i.webp -o $PFX.$i.png
done

convert $PFX.*.png -delay $DELAY -loop $LOOP $PFX.gif
rm $PFX.[0-9]*.png $PFX.[0-9]*.webp
popd > /dev/null
