#!/bin/bash
export URLS="$*";
/usr/local/bin/youtube-dl --user-agent "Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)" -o '%(title)s.%(ext)s' --extract-audio --audio-format=mp3 $URLS
