#!/bin/bash
sudo iptables -t nat -I PREROUTING --src 0.0.0.0/0 --dst 127.0.0.2 -p tcp --dport 22 -j REDIRECT --to-ports 2220
sudo iptables -t nat -I OUTPUT     --src 0.0.0.0/0 --dst 127.0.0.2 -p tcp --dport 22 -j REDIRECT --to-ports 2220
